easy_admin:
  entities:
    System:
      class: App\Entity\System
    Epic:
      class: App\Entity\Epic
      label: 'Epic list'
      list:
        actions: ['show']
        fields:
        - name
        - system
      show:
        fields:
        - name
        - system
        - games
    Games:
      class: App\Entity\Game
